#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Tue Jun  1 21:03:18 2010

import wx

# begin wxGlade: extracode
import matplot
# end wxGlade



class SplitDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SplitDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_30 = wx.StaticText(self, -1, "Date")
        self.datepicker_date = wx.DatePickerCtrl(self, -1)
        self.label_31 = wx.StaticText(self, -1, "Share")
        self.combobox_assets = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_32 = wx.StaticText(self, -1, "X shares ..")
        self.textctrl_x = wx.TextCtrl(self, -1, "1")
        self.label_33 = wx.StaticText(self, -1, ".. for Y")
        self.textctrl_y = wx.TextCtrl(self, -1, "1")
        self.label_34 = wx.StaticText(self, -1, "Price after split")
        self.textctrl_price = wx.TextCtrl(self, -1, "1.0")
        self.static_line_5 = wx.StaticLine(self, -1)
        self.button_9 = wx.Button(self, -1, "Split Asset")
        self.button_10 = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnSplitButtonClicked, self.button_9)
        self.Bind(wx.EVT_BUTTON, self.OnCancelButtonClicked, self.button_10)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SplitDialog.__set_properties
        self.SetTitle("dialog_5")
        self.combobox_assets.SetMinSize((250, -1))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SplitDialog.__do_layout
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_15 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_14 = wx.GridSizer(5, 2, 0, 0)
        grid_sizer_14.Add(self.label_30, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_14.Add(self.datepicker_date, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_14.Add(self.label_31, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_14.Add(self.combobox_assets, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_14.Add(self.label_32, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_14.Add(self.textctrl_x, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_14.Add(self.label_33, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_14.Add(self.textctrl_y, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_14.Add(self.label_34, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_14.Add(self.textctrl_price, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_7.Add(grid_sizer_14, 1, wx.ALL|wx.EXPAND, 5)
        sizer_7.Add(self.static_line_5, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 10)
        grid_sizer_15.Add(self.button_9, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_15.Add(self.button_10, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_7.Add(grid_sizer_15, 1, wx.ALL|wx.EXPAND, 5)
        self.SetSizer(sizer_7)
        sizer_7.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnSplitButtonClicked(self, event): # wxGlade: SplitDialog.<event_handler>
		#print "Event handler `OnSplitButtonClicked' not implemented"
        #event.Skip()
		self.EndModal(wx.ID_OK)

    def OnCancelButtonClicked(self, event): # wxGlade: SplitDialog.<event_handler>
		#print "Event handler `OnCancelButtonClicked' not implemented"
        #event.Skip()
		self.EndModal(wx.ID_CANCEL)

# end of class SplitDialog


class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # content of this block not found: did you rename this class?
        pass

    def __set_properties(self):
        # content of this block not found: did you rename this class?
        pass

    def __do_layout(self):
        # content of this block not found: did you rename this class?
        pass

# end of class MyDialog


class GenericTransferDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GenericTransferDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_21 = wx.StaticText(self, -1, "Description")
        self.textctrl_description = wx.TextCtrl(self, -1, "")
        self.label_22 = wx.StaticText(self, -1, "Date")
        self.datepicker_date = wx.DatePickerCtrl(self, -1)
        self.label_23 = wx.StaticText(self, -1, "FROM account/share")
        self.combobox_fromaccount = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_24 = wx.StaticText(self, -1, "Amount/quantity")
        self.textctrl_fromamount = wx.TextCtrl(self, -1, "")
        self.label_25 = wx.StaticText(self, -1, "Price")
        self.textctrl_fromprice = wx.TextCtrl(self, -1, "")
        self.label_26 = wx.StaticText(self, -1, "Commission")
        self.textctrl_fromcommission = wx.TextCtrl(self, -1, "")
        self.label_27 = wx.StaticText(self, -1, "TO account/share")
        self.combobox_toaccount = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_28 = wx.StaticText(self, -1, "Amount/quantity")
        self.textctrl_toamount = wx.TextCtrl(self, -1, "")
        self.label_29 = wx.StaticText(self, -1, "Price")
        self.textctrl_toprice = wx.TextCtrl(self, -1, "")
        self.label_30 = wx.StaticText(self, -1, "Commission")
        self.textctrl_tocommission = wx.TextCtrl(self, -1, "")
        self.static_line_4 = wx.StaticLine(self, -1)
        self.button_7 = wx.Button(self, -1, "Add")
        self.button_8 = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnAddClicked, self.button_7)
        self.Bind(wx.EVT_BUTTON, self.OnCancelClicked, self.button_8)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: GenericTransferDialog.__set_properties
        self.SetTitle("dialog_4")
        self.textctrl_description.SetMinSize((250, -1))
        self.combobox_fromaccount.SetMinSize((250, -1))
        self.combobox_toaccount.SetMinSize((250, -1))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: GenericTransferDialog.__do_layout
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_12 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_11 = wx.GridSizer(10, 2, 0, 0)
        grid_sizer_11.Add(self.label_21, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.textctrl_description, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.label_22, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.datepicker_date, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.label_23, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.combobox_fromaccount, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.label_24, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.textctrl_fromamount, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.label_25, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.textctrl_fromprice, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.label_26, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.textctrl_fromcommission, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.label_27, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.combobox_toaccount, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.label_28, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.textctrl_toamount, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.label_29, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.textctrl_toprice, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.label_30, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_11.Add(self.textctrl_tocommission, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_6.Add(grid_sizer_11, 0, wx.ALL|wx.EXPAND, 5)
        sizer_6.Add(self.static_line_4, 0, wx.EXPAND, 0)
        grid_sizer_12.Add(self.button_7, 0, wx.ALL|wx.ALIGN_RIGHT, 5)
        grid_sizer_12.Add(self.button_8, 0, wx.ALL, 5)
        sizer_6.Add(grid_sizer_12, 0, wx.ALL|wx.EXPAND, 15)
        self.SetSizer(sizer_6)
        sizer_6.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnAddClicked(self, event): # wxGlade: GenericTransferDialog.<event_handler>
        #print "Event handler `OnAddClicked' not implemented"
        #event.Skip()
		self.EndModal(wx.ID_OK)

    def OnCancelClicked(self, event): # wxGlade: GenericTransferDialog.<event_handler>
        #print "Event handler `OnCancelClicked' not implemented"
        #event.Skip()
		self.EndModal(wx.ID_CANCEL)

# end of class GenericTransferDialog


class ShareDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ShareDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_13 = wx.StaticText(self, -1, "Description")
        self.textctrl_description = wx.TextCtrl(self, -1, "")
        self.label_14 = wx.StaticText(self, -1, "Date")
        self.datepicker_date = wx.DatePickerCtrl(self, -1)
        self.label_15 = wx.StaticText(self, -1, "Transaction type")
        self.combobox_transactiontypes = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_16 = wx.StaticText(self, -1, "Share")
        self.combobox_shares = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_17 = wx.StaticText(self, -1, "Number of shares")
        self.textctrl_quantity = wx.TextCtrl(self, -1, "", style=wx.TE_RIGHT)
        self.label_18 = wx.StaticText(self, -1, "Price")
        self.textctrl_price = wx.TextCtrl(self, -1, "", style=wx.TE_RIGHT)
        self.label_19 = wx.StaticText(self, -1, "Commission")
        self.textctrl_commission = wx.TextCtrl(self, -1, "", style=wx.TE_RIGHT)
        self.label_20 = wx.StaticText(self, -1, "Account")
        self.combobox_accounts = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN)
        self.static_line_3 = wx.StaticLine(self, -1)
        self.button_3 = wx.Button(self, -1, "Add")
        self.button_4 = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnAddButtonClicked, self.button_3)
        self.Bind(wx.EVT_BUTTON, self.OnCancelButtonClicked, self.button_4)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ShareDialog.__set_properties
        self.SetTitle("Share transaction")
        self.textctrl_description.SetMinSize((250, -1))
        self.combobox_shares.SetMinSize((250, -1))
        self.combobox_accounts.SetMinSize((250, -1))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ShareDialog.__do_layout
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_9 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_10 = wx.GridSizer(8, 2, 0, 0)
        grid_sizer_10.Add(self.label_13, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_10.Add(self.textctrl_description, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_10.Add(self.label_14, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_10.Add(self.datepicker_date, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_10.Add(self.label_15, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_10.Add(self.combobox_transactiontypes, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_10.Add(self.label_16, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_10.Add(self.combobox_shares, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_10.Add(self.label_17, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_10.Add(self.textctrl_quantity, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_10.Add(self.label_18, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_10.Add(self.textctrl_price, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_10.Add(self.label_19, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_10.Add(self.textctrl_commission, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_10.Add(self.label_20, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_10.Add(self.combobox_accounts, 0, wx.ALL, 5)
        sizer_5.Add(grid_sizer_10, 0, wx.ALL|wx.EXPAND, 5)
        sizer_5.Add(self.static_line_3, 0, wx.EXPAND, 0)
        grid_sizer_9.Add(self.button_3, 0, wx.ALL|wx.ALIGN_RIGHT, 5)
        grid_sizer_9.Add(self.button_4, 0, wx.ALL, 5)
        sizer_5.Add(grid_sizer_9, 0, wx.ALL|wx.EXPAND, 15)
        self.SetSizer(sizer_5)
        sizer_5.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnAddButtonClicked(self, event): # wxGlade: ShareDialog.<event_handler>
        #print "Event handler `OnAddButtonClicked' not implemented"
        #event.Skip()
	self.EndModal(wx.ID_OK)

    def OnCancelButtonClicked(self, event): # wxGlade: ShareDialog.<event_handler>
        #print "Event handler `OnCancelButtonClicked' not implemented"
        #event.Skip()
	self.EndModal(wx.ID_CANCEL)

# end of class ShareDialog


class TransferDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: TransferDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_3 = wx.StaticText(self, -1, "Description")
        self.textctrl_description = wx.TextCtrl(self, -1, "")
        self.label_4 = wx.StaticText(self, -1, "Date")
        self.datepicker_date = wx.DatePickerCtrl(self, -1)
        self.label_10 = wx.StaticText(self, -1, "Amount (currency as accounts)")
        self.textctrl_amount = wx.TextCtrl(self, -1, "", style=wx.TE_RIGHT)
        self.label_11 = wx.StaticText(self, -1, "From account")
        self.combobox_fromaccount = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_12 = wx.StaticText(self, -1, "To account")
        self.combobox_toaccount = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN)
        self.static_line_2 = wx.StaticLine(self, -1)
        self.button_1 = wx.Button(self, -1, "Add")
        self.button_2 = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnAddClicked, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.OnCancelClicked, self.button_2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: TransferDialog.__set_properties
        self.SetTitle("Transfer money")
        self.textctrl_description.SetMinSize((250, -1))
        self.combobox_fromaccount.SetMinSize((250, -1))
        self.combobox_toaccount.SetMinSize((250, -1))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: TransferDialog.__do_layout
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_8 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_7 = wx.GridSizer(5, 2, 0, 0)
        grid_sizer_7.Add(self.label_3, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_7.Add(self.textctrl_description, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_7.Add(self.label_4, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_7.Add(self.datepicker_date, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_7.Add(self.label_10, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_7.Add(self.textctrl_amount, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_7.Add(self.label_11, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_7.Add(self.combobox_fromaccount, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_7.Add(self.label_12, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_7.Add(self.combobox_toaccount, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_4.Add(grid_sizer_7, 0, wx.ALL|wx.EXPAND, 5)
        sizer_4.Add(self.static_line_2, 0, wx.EXPAND, 0)
        grid_sizer_8.Add(self.button_1, 0, wx.RIGHT|wx.ALIGN_RIGHT, 5)
        grid_sizer_8.Add(self.button_2, 0, wx.LEFT, 5)
        sizer_4.Add(grid_sizer_8, 1, wx.ALL|wx.EXPAND, 15)
        self.SetSizer(sizer_4)
        sizer_4.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnAddClicked(self, event): # wxGlade: TransferDialog.<event_handler>
        #print "Event handler `OnAddClicked' not implemented!"
        #event.Skip()
	self.EndModal(wx.ID_OK)

    def OnCancelClicked(self, event): # wxGlade: TransferDialog.<event_handler>
        #print "Event handler `OnCancelClicked' not implemented!"
        #event.Skip()
	self.EndModal(wx.ID_CANCEL)

# end of class TransferDialog


class FrugalFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FrugalFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_4 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_3 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        global ID_NEW; ID_NEW = wx.NewId()
        global ID_OPEN; ID_OPEN = wx.NewId()
        global ID_SAVE; ID_SAVE = wx.NewId()
        global ID_QUIT; ID_QUIT = wx.NewId()
        global ID_TRANSACTION; ID_TRANSACTION = wx.NewId()
        global ID_SPLIT; ID_SPLIT = wx.NewId()
        global ID_ADDINCOMEMNU; ID_ADDINCOMEMNU = wx.NewId()
        global ID_ADDEXPENSEMNU; ID_ADDEXPENSEMNU = wx.NewId()
        global ID_TRANSFERMONEYMNU; ID_TRANSFERMONEYMNU = wx.NewId()
        global ID_BUYSELLSHARESMNU; ID_BUYSELLSHARESMNU = wx.NewId()
        global ID_ADDQUOTES; ID_ADDQUOTES = wx.NewId()
        global ID_DOWNLOADQUOTESMNU; ID_DOWNLOADQUOTESMNU = wx.NewId()
        global ID_RECALCULATEMNU; ID_RECALCULATEMNU = wx.NewId()
        global ID_ADDHOUSE; ID_ADDHOUSE = wx.NewId()
        global ID_ADDLIAB; ID_ADDLIAB = wx.NewId()
        global ID_USERSGUIDE; ID_USERSGUIDE = wx.NewId()
        global ID_UPDATE; ID_UPDATE = wx.NewId()
        global ID_ABOUT; ID_ABOUT = wx.NewId()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(ID_NEW, "New project...", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(ID_OPEN, "Open project...", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(ID_SAVE, "Save project...", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(ID_QUIT, "Quit", "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(ID_TRANSACTION, "Transaction Tool...", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(ID_SPLIT, "Stock Split Tool...", "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "Tools")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(ID_ADDINCOMEMNU, "Add income...", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(ID_ADDEXPENSEMNU, "Add expense...", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(ID_TRANSFERMONEYMNU, "Transfer money...", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(ID_BUYSELLSHARESMNU, "Buy/Sell shares...", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(ID_ADDQUOTES, "Add quotes...", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(ID_DOWNLOADQUOTESMNU, "Download quotes", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(ID_RECALCULATEMNU, "Recalculate", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(ID_ADDHOUSE, "Add House or Car...", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(ID_ADDLIAB, "Add Loan or Liability...", "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "Project")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(ID_USERSGUIDE, "User's Guide", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(ID_UPDATE, "Search for updates", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(ID_ABOUT, "About Frugal", "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "About")
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.frame_1_statusbar = self.CreateStatusBar(1, 0)
        
        # Tool Bar
        self.frame_1_toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL|wx.TB_3DBUTTONS|wx.TB_TEXT)
        self.SetToolBar(self.frame_1_toolbar)
        global ID_ADDINCOME; ID_ADDINCOME = wx.NewId()
        global ID_ADDEXPENSE; ID_ADDEXPENSE = wx.NewId()
        global ID_TRANSFERMONEY; ID_TRANSFERMONEY = wx.NewId()
        global ID_BUYSELLSHARES; ID_BUYSELLSHARES = wx.NewId()
        global ID_DOWNLOADQUOTES; ID_DOWNLOADQUOTES = wx.NewId()
        global ID_RECALCULATE; ID_RECALCULATE = wx.NewId()
        self.frame_1_toolbar.AddLabelTool(ID_ADDINCOME, "Income", (wx.ArtProvider.GetBitmap(wx.ART_TICK_MARK,wx.ART_TOOLBAR)), wx.NullBitmap, wx.ITEM_NORMAL, "Add income transaction", "Add income transaction")
        self.frame_1_toolbar.AddLabelTool(ID_ADDEXPENSE, "Expense", (wx.ArtProvider.GetBitmap(wx.ART_TICK_MARK,wx.ART_TOOLBAR)), wx.NullBitmap, wx.ITEM_NORMAL, "Add expense transaction", "Add expense transaction")
        self.frame_1_toolbar.AddLabelTool(ID_TRANSFERMONEY, "Transfer Money", (wx.ArtProvider.GetBitmap(wx.ART_TICK_MARK,wx.ART_TOOLBAR)), wx.NullBitmap, wx.ITEM_NORMAL, "Transfer money between accounts", "Transfer money between accounts")
        self.frame_1_toolbar.AddLabelTool(ID_BUYSELLSHARES, "Buy/Sell Shares", (wx.ArtProvider.GetBitmap(wx.ART_TICK_MARK,wx.ART_TOOLBAR)), wx.NullBitmap, wx.ITEM_NORMAL, "Buy or sell shares", "Buy or sell shares")
        self.frame_1_toolbar.AddLabelTool(ID_DOWNLOADQUOTES, "Download Quotes", (wx.ArtProvider.GetBitmap(wx.ART_TICK_MARK,wx.ART_TOOLBAR)), wx.NullBitmap, wx.ITEM_NORMAL, "Download quotes from the internet", "Download quotes from the internet")
        self.frame_1_toolbar.AddSeparator()
        self.frame_1_toolbar.AddLabelTool(ID_RECALCULATE, "Recalculate", (wx.ArtProvider.GetBitmap(wx.ART_TICK_MARK,wx.ART_TOOLBAR)), wx.NullBitmap, wx.ITEM_NORMAL, "Recalculate whole project", "Recalculate whole project")
        # Tool Bar end
        self.listctrl_balance1 = wx.ListCtrl(self.notebook_1_pane_1, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.pieplot_balance2 = matplot.pieplot(self.notebook_1_pane_1, -1)
        self.pieplot_balance3 = matplot.pieplot(self.notebook_1_pane_1, -1)
        self.lineplot_balance4 = matplot.lineplot(self.notebook_1_pane_1, -1)
        self.listctrl_income1 = wx.ListCtrl(self.notebook_1_pane_2, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.pieplot_income2 = matplot.pieplot(self.notebook_1_pane_2, -1)
        self.listctrl_income3 = wx.ListCtrl(self.notebook_1_pane_2, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.lineplot_income4 = matplot.lineplot(self.notebook_1_pane_2, -1)
        global ID_PORTFOLIOLIST; ID_PORTFOLIOLIST = wx.NewId()
        self.listctrl_portfolio1 = wx.ListCtrl(self.notebook_1_pane_3, ID_PORTFOLIOLIST, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.pieplot_portfolio2 = matplot.pieplot(self.notebook_1_pane_3, -1)
        self.pieplot_portfolio3 = matplot.pieplot(self.notebook_1_pane_3, -1)
        self.lineplot_portfolio4 = matplot.lineplot(self.notebook_1_pane_3, -1)
        self.listctrl_budget1 = wx.ListCtrl(self.notebook_1_pane_4, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.pieplot_budget2 = matplot.pieplot(self.notebook_1_pane_4, -1)
        self.pieplot_budget3 = matplot.pieplot(self.notebook_1_pane_4, -1)
        self.pieplot_budget4 = matplot.pieplot(self.notebook_1_pane_4, -1)
        self.notebook_1_pane_5 = wx.Panel(self.notebook_1, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FrugalFrame.__set_properties
        self.SetTitle("Frugal Finance")
        self.SetSize((800, 650))
        self.frame_1_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_1_statusbar_fields = [""]
        for i in range(len(frame_1_statusbar_fields)):
            self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
        self.frame_1_toolbar.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FrugalFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_13 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_3 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_2 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_1 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_1.Add(self.listctrl_balance1, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.pieplot_balance2, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.pieplot_balance3, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.lineplot_balance4, 1, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(grid_sizer_1)
        grid_sizer_2.Add(self.listctrl_income1, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.pieplot_income2, 1, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.listctrl_income3, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.lineplot_income4, 1, wx.EXPAND, 0)
        self.notebook_1_pane_2.SetSizer(grid_sizer_2)
        grid_sizer_3.Add(self.listctrl_portfolio1, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.pieplot_portfolio2, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.pieplot_portfolio3, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.lineplot_portfolio4, 1, wx.EXPAND, 0)
        self.notebook_1_pane_3.SetSizer(grid_sizer_3)
        grid_sizer_13.Add(self.listctrl_budget1, 1, wx.EXPAND, 0)
        grid_sizer_13.Add(self.pieplot_budget2, 1, wx.EXPAND, 0)
        grid_sizer_13.Add(self.pieplot_budget3, 1, wx.EXPAND, 0)
        grid_sizer_13.Add(self.pieplot_budget4, 1, wx.EXPAND, 0)
        self.notebook_1_pane_4.SetSizer(grid_sizer_13)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Balance Sheet")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Income Statement")
        self.notebook_1.AddPage(self.notebook_1_pane_3, "Stock Portfolio")
        self.notebook_1.AddPage(self.notebook_1_pane_4, "Show Budget")
        self.notebook_1.AddPage(self.notebook_1_pane_5, "Transactions")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class FrugalFrame


class ShareFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ShareFrame.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.STAY_ON_TOP|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.share_sharename = wx.StaticText(self, -1, "Share name (ticker)")
        self.share_shareprice = wx.StaticText(self, -1, "price")
        self.share_averageprice = wx.StaticText(self, -1, "Average price per share (price)")
        self.label_1 = wx.StaticText(self, -1, "")
        self.share_holdings = wx.StaticText(self, -1, "Holding x shares")
        self.label_2 = wx.StaticText(self, -1, "")
        self.share_mixplot1 = matplot.mixplot(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ShareFrame.__set_properties
        self.SetTitle("Share Information")
        self.SetSize((700, 500))
        self.SetFocus()
        self.share_sharename.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.share_shareprice.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ShareFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_4 = wx.GridSizer(3, 2, 0, 0)
        grid_sizer_4.Add(self.share_sharename, 0, 0, 0)
        grid_sizer_4.Add(self.share_shareprice, 0, wx.ALIGN_RIGHT, 0)
        grid_sizer_4.Add(self.share_averageprice, 0, 0, 0)
        grid_sizer_4.Add(self.label_1, 0, 0, 0)
        grid_sizer_4.Add(self.share_holdings, 0, 0, 0)
        grid_sizer_4.Add(self.label_2, 0, 0, 0)
        sizer_2.Add(grid_sizer_4, 0, wx.ALL|wx.EXPAND, 8)
        sizer_2.Add(self.share_mixplot1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class ShareFrame


class AddDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AddDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_5 = wx.StaticText(self, -1, "Description")
        self.textctrl_description = wx.TextCtrl(self, -1, "")
        self.label_6 = wx.StaticText(self, -1, "Date")
        self.datepicker_date = wx.DatePickerCtrl(self, -1)
        self.label_7 = wx.StaticText(self, -1, "Amount (currency as account)")
        self.textctrl_amount = wx.TextCtrl(self, -1, "", style=wx.TE_RIGHT)
        self.label_8 = wx.StaticText(self, -1, "Account")
        self.combobox_accounts = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_SIMPLE|wx.CB_READONLY)
        self.label_9 = wx.StaticText(self, -1, "Transaction type")
        self.combobox_transactiontypes = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_SIMPLE|wx.CB_READONLY)
        self.static_line_1 = wx.StaticLine(self, -1)
        self.button_5 = wx.Button(self, -1, "Add")
        self.button_6 = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnAddClicked, self.button_5)
        self.Bind(wx.EVT_BUTTON, self.OnCancelClicked, self.button_6)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AddDialog.__set_properties
        self.SetTitle("Add transaction")
        self.textctrl_description.SetMinSize((250, -1))
        self.combobox_accounts.SetMinSize((250, -1))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AddDialog.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_6 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_5 = wx.GridSizer(5, 2, 0, 0)
        grid_sizer_5.Add(self.label_5, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_5.Add(self.textctrl_description, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_5.Add(self.label_6, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_5.Add(self.datepicker_date, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_5.Add(self.label_7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_5.Add(self.textctrl_amount, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_5.Add(self.label_8, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_5.Add(self.combobox_accounts, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_5.Add(self.label_9, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_5.Add(self.combobox_transactiontypes, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_3.Add(grid_sizer_5, 0, wx.ALL|wx.EXPAND, 5)
        sizer_3.Add(self.static_line_1, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 10)
        grid_sizer_6.Add(self.button_5, 0, wx.RIGHT|wx.ALIGN_RIGHT, 5)
        grid_sizer_6.Add(self.button_6, 0, wx.LEFT, 5)
        sizer_3.Add(grid_sizer_6, 1, wx.ALL|wx.EXPAND, 15)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnAddClicked(self, event): # wxGlade: AddDialog.<event_handler>
        #print "Event handler `OnAddClicked' not implemented!"
        #event.Skip()
	self.EndModal(wx.ID_OK)

    def OnCancelClicked(self, event): # wxGlade: AddDialog.<event_handler>
        #print "Event handler `OnCancelClicked' not implemented!"
        #event.Skip()
	self.EndModal(wx.ID_CANCEL)

# end of class AddDialog


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = FrugalFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
